---
title: "Biden_twitter_analysis"
---

```{r}
install.packages("rtweet")
install.packages("httpuv")
```
```{r}
install.packages("maps")
```
```{r}
install.packages("ggmap")
```


```{r}
library(rtweet)
library(rtweet)
library(dplyr)
library(maps)
library(ggmap)
```




```{r}
biden_tweets3 <- search_tweets(q ="biden OR joebiden", lang = "en" , geocode = lookup_coords("usa"), n = 300000, include_rts = FALSE, retryonratelimit = TRUE)

biden_tweets3 <- lat_lng(biden_tweets3)
```

```{r, message=F, warning=F}

tweets_cleaned <- select(tweets,user_id,status_id,created_at, screen_name,text,lang,location,lat,lng)   %>% filter(!is.na(lat)) 
```


```{r}
par(mar = c(0, 0, 0, 0))
maps::map("state", lwd = .25)
## plot lat and lng points onto state map
with(tweets_cleaned_final, points(lng, lat, pch = 20, cex = .75, col = rgb(0, .3, .7, .5)))

```


```{r}
for (i in 1:10152) {
  tweets_cleaned$GoogleMapsLocation[i] = revgeocode(c(tweets_cleaned$lng[i],tweets_cleaned$lat[i]))
}

```

```{r}
for (i in 1:10152) {
  tmp = strsplit(tweets_cleaned$GoogleMapsLocation[i], ", ")[[1]]
  tweets_cleaned$country[i] = tmp[4]
  tweets_cleaned$zip[i] = strsplit(tmp[3], " ")[[1]][2]
  tweets_cleaned$state[i] = strsplit(tmp[3], " ")[[1]][1]
}

```

```{r}
tweets_cleaned_final <- tweets_cleaned %>% filter(country == "USA")
tweets_final = distinct(tweets_cleaned_final, user_id, .keep_all = TRUE)
```


```{r}
write_as_csv(tweets_final,file = "tweets_final.csv")

```
